# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y6kEWwYqYegICIIRLC8ES8L6Df6n_lps
"""

!unzip air-pollution-in-seoul.zip

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np 
# % matplotlib inline
import matplotlib.pyplot as plt

data = pd.read_csv('AirPollutionSeoul/Measurement_summary.csv')
data.head()

df=data['PM10']
df=df.values
df=df.reshape(df.shape[0],1)
print(df.shape)

list_=[]
for i in range (0,df.shape[0]):
  list_.append(df[i][0])
print(len(list_))

window_size=5
y=[]
for i in range (0,len(list_)-5):
  x=list_[i:i+window_size]
  y.append(x)
print(len(y),y[0])

matrix=np.matrix(y)
print(matrix.shape)

print(matrix[:,4])

from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
X_train, X_test, y_train, y_test = train_test_split(matrix[:,0:4],matrix[:,4],test_size=0.33, random_state=42)
lm = linear_model.LinearRegression()
model = lm.fit(X_train,y_train)
prediction=model.predict(X_test)
print(prediction.shape,prediction[0:5])

print(model.score(X_train,y_train))
print(model.intercept_)
print(model.coef_)

print(mean_squared_error(y_test,prediction)**0.5)
print(r2_score(y_test,prediction))

